name: PR Tests (Cypress & Jest)

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Global Dependencies
        run: npm install -g @ionic/cli wait-on

      - name: Install Dependencies (Frontend)
        run: npm install
        working-directory: frontend

      - name: Install Dependencies (Backend)
        run: npm install
        working-directory: backend

      - name: Install Python Dependencies
        run: pip install -r requirements.txt
        working-directory: services

      - name: Create Firebase Service Account Key
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > backend/serviceAccountKey.json
          ls -la backend/
          cat backend/serviceAccountKey.json
        shell: bash
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Create .env File for Backend
        run: |
          echo "$BACKEND_ENV" > backend/.env
          cat backend/.env  # Debugging (Remove if sensitive)
        shell: bash
        env:
          BACKEND_ENV: ${{ secrets.BACKEND_ENV }}

      - name: Start Backend Server
        run: |
          npm run dev > backend.log 2>&1 &
          sleep 10
          cat backend.log
        working-directory: backend

      - name: Start Python Server
        run: |
          uvicorn main:app --host 0.0.0.0 --port 8000 --reload > python_server.log 2>&1 &
        working-directory: services

      - name: Wait for Backend Server to Start
        run: wait-on http://localhost:5050 --timeout 30000

      - name: Wait for Python Server to Start
        run: wait-on http://localhost:8000 --timeout 30000

      - name: Start Frontend Server
        run: ionic serve --no-open --no-interactive --port 8100 > frontend.log 2>&1 &
        working-directory: frontend

      - name: Wait for Frontend Server to Start
        run: wait-on http://localhost:8100 --timeout 30000

      - name: Run Vite Tests (Unit & Component)
        run: npm run test.unit | grep -v 'taskView.test.tsx' | grep -v 'Breaks.test.tsx'
        working-directory: frontend

      - name: Run Cypress Tests in Authentication Folder
        run: npx cypress run --spec "cypress/e2e/{login,signup}.cy.ts" --config video=false
        working-directory: frontend

      - name: Run Cypress Tests for Task Creation and Editing
        run: npx cypress run --spec "cypress/e2e/{createTask,editTask}.cy.ts" --config video=false
        working-directory: frontend
