name: PR Tests (Cypress & Jest)

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies (Frontend)
        run: npm install
        working-directory: frontend

      - name: Install Dependencies (Backend)
        run: npm install
        working-directory: backend

      - name: Start Backend Server
        run: npm run dev &
        working-directory: backend

      - name: Start Frontend Server
        run: ionic serve --no-open --no-interactive --port 8100 &
        working-directory: frontend

      - name: Wait for Backend and Frontend to be Ready
        run: npx wait-on http://localhost:8100 http://localhost:5050
        working-directory: frontend

      - name: Run Specific Cypress Test
        run: npx cypress run --spec cypress/e2e/login.cy.ts --config video=false
        working-directory: frontend
